AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Tides API SAM Application

Parameters:
  Stage:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - local

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Architectures:
      - arm64
    AutoPublishAlias: live
    SnapStart:
      ApplyOn: PublishedVersions
    Environment:
      Variables:
        STATION_LIST_BUCKET: !Ref StationListBucket
        AWS_REGION: !Ref AWS::Region
        ENV: !If [ IsLocal, "development", "prod" ]
        DYNAMODB_ENDPOINT: !If [ IsLocal, "http://dynamodb-local:8000", "" ]
        ALLOWED_ORIGINS: !If [ IsLocal, "http://localhost:3000", "https://app.flowebb.com" ]
        LOG_LEVEL: "debug"

  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'http://localhost:3000'"

Resources:
  StationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .aws-sam/build/StationsFunction
      Handler: bootstrap
      Runtime: provided.al2
      Events:
        StationsApi:
          Type: Api
          Properties:
            Path: /api/stations
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
        - S3ReadPolicy:
            BucketName: !Ref StationListBucket
        - S3WritePolicy:
            BucketName: !Ref StationListBucket

  TidesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .aws-sam/build/TidesFunction
      Handler: bootstrap
      Runtime: provided.al2
      Events:
        TidesApi:
          Type: Api
          Properties:
            Path: /api/tides
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
        - S3ReadPolicy:
            BucketName: !Ref StationListBucket

  StationListBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-station-list-cache
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldFiles
            Status: Enabled
            ExpirationInDays: 7

Conditions:
  IsLocal:
    Fn::Equals:
      - !Ref Stage
      - local
