AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Tides API SAM Application

Globals:
  Function:
    Timeout: 120
    MemorySize: 512
    Runtime: java11
    Architectures:
      - arm64
    AutoPublishAlias: live
    Environment:
      Variables:
        # Shared variables that are always set
        STATION_LIST_BUCKET: !Ref StationListBucket
        AWS_REGION: !Ref AWS::Region
        # Conditional variables based on environment
        DYNAMODB_ENDPOINT: !If
          - IsLocal
          - "http://dynamodb-local:8000"
          - ""
        ALLOWED_ORIGINS: !If
          - IsLocal
          - "'http://localhost:3000'"
          - "'https://app.flowebb.com'"

  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'http://localhost:3000'"

Resources:
  StationListBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-station-list-cache
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldFiles
            Status: Enabled
            ExpirationInDays: 7

  TidesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend
      Handler: com.flowebb.lambda.TidesLambda::handleRequest
      Events:
        TidesApi:
          Type: Api
          Properties:
            Path: /api/tides
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
        - S3ReadPolicy:
            BucketName: !Ref StationListBucket
        - S3WritePolicy:
            BucketName: !Ref StationListBucket

  StationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend
      Handler: com.flowebb.lambda.StationsLambda::handleRequest
      Events:
        StationsApi:
          Type: Api
          Properties:
            Path: /api/stations
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
        - S3ReadPolicy:
            BucketName: !Ref StationListBucket
        - S3WritePolicy:
            BucketName: !Ref StationListBucket

